# Generated by Django 4.0.4 on 2022-05-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userlinks_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.themecolor'),
        ),
    ]
