# Generated by Django 4.0.4 on 2022-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profil_color_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='color',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
