# Generated by Django 4.0.4 on 2022-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profil_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
